<?php

class SportRelais extends Sport
{
    private $distance;

    /**
     * @param $distance
     */
    public function __construct(string $nomSport , int $nbJoueurs , $distance)
    {
        parent::__construct($nomSport,$nbJoueurs);
        $this->distance = $distance;
    }
    /**
     * @return mixed
     */

    public function getDistance()
    {
        return $this->distance;
    }

    public function getDescription(): string
    {
        return parent::getDescription()."<br>distance = ".$this->distance; // TODO: Change the autogenerated stub
    }
}


