<?php

class SportBallon extends Sport
{
    private  $largeur;
    private  $longueur;

    /**
     * @param int $largeur
     * @param int $longueur
     */
    public function __construct(string $nomSport , int $nbJoueurs ,int $largeur, int $longueur)
    {
        parent::__construct($nomSport,$nbJoueurs);
        $this->largeur = $largeur;
        $this->longueur = $longueur;
    }

    /**
     * @return int
     */
    public function getLargeur(): int
    {
        return $this->largeur;
    }

    /**
     * @return int
     */
    public function getLongueur(): int
    {
        return $this->longueur;
    }

    public function getDescription(): string
    {
        return parent::getDescription()." longueur = ".$this->longueur." largeur = ".$this->largeur; // TODO: Change the autogenerated stub
    }

}